# .github/workflows/nag.yml
name: joshbot-scheduled

on:
  # Every 30 minutes.  Change */30 to */15 for 15-min, or use any cron you like.
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:        # keeps the green “Run workflow” button

jobs:
  nudge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & send
        run: |
          pip install python-dotenv requests
          python nagbot.py
        env:
          RESEND_API_KEY:    ${{ secrets.RESEND_API_KEY }}
          FRIEND_EMAIL:      ${{ secrets.FRIEND_EMAIL }}
          FRIEND_PHONE_SMTP: ${{ secrets.FRIEND_PHONE_SMTP }}
          FRIEND_PHONE_NUM:  ${{ secrets.FRIEND_PHONE_NUM }}
