name: daily-nudge

on:
  push:               # run on every commit to main
  workflow_dispatch:  # show the “Run workflow” button
  schedule:
    - cron: '0 13 * * *'   # 09:00 EDT = 13:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps & run JOSHBOT
        run: |
          pip install simplelogin resend schedule python-dotenv requests
          python nagbot.py          # or josbot.py if you renamed it
        env: ${{ secrets }}
