name: daily-nudge
on:
  push:            # <— new line
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'          # 09:00 EDT = 13:00 UTC
  workflow_dispatch:              # lets you run it manually
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
            - run: |
          pip install simplelogin resend schedule python-dotenv requests
          python nagbot.py
        env: ${{ secrets }}
