# .github/workflows/nag.yml
name: joshbot-manual

on:
  workflow_dispatch:   # ⬅️  this puts the green "Run workflow" button in Actions

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps & send once
        run: |
          pip install resend schedule python-dotenv requests
          python nagbot.py          # <- or josbot.py if you changed the filename
        env: ${{ secrets }}
