# .github/workflows/nag.yml
name: joshbot-scheduled

on:
  schedule:
    # every 10 minutes  (00, 10, 20 … UTC)
    - cron: "*/10 * * * *"
  workflow_dispatch:        # keeps the green “Run workflow” button

jobs:
  nudge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & send
        run: |
          pip install python-dotenv requests
          python nagbot.py
        env:
          RESEND_API_KEY:      ${{ secrets.RESEND_API_KEY }}
          FRIEND_EMAILS:       ${{ secrets.FRIEND_EMAILS }}
          FRIEND_PHONE_SMTPS:  ${{ secrets.FRIEND_PHONE_SMTPS }}
          FRIEND_PHONE_NUMS:   ${{ secrets.FRIEND_PHONE_NUMS }}
